vagrant/tradyfit/app/msg/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextAreaField, SubmitField
from wtforms.validators import Required, Length, Regexp


class MessageForm(Form):
  subject = TextAreaField('Subject (*)', validators=[Required(), Length(3,120),
                            Regexp('^[A-Za-z0-9][.\-\:\!\' \w]+$', 0,
                                  'Subject must have only letters,'
                                  ' numbers, dots, dashes or underscores')])
  description = TextAreaField('Description', validators=[Length(0,500)])
  submit = SubmitField('Send')

vagrant/tradyfit/app/msg/__init__.py
from flask import Blueprint

msg = Blueprint('msg', __name__)

from . import views

vagrant/tradyfit/app/msg/views.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask.ext.login import current_user, login_required
from . import msg
from .. import db
from .forms import MessageForm
from ..models import Item, Message


@msg.route('/msg/create/<int:id>', methods=['GET', 'POST'])
@login_required
def create(id): # pylint: disable=W0622
  item = Item.query.get_or_404(id)
  form = MessageForm()

  if form.validate_on_submit():
    msg = Message(subject=form.subject.data, description=form.description.data,
                  sender_id=current_user.id, receiver_id=item.user_id,
                  item_id=item.id)
    db.session.add(msg)
    db.session.commit()
    flash('Your message has been sent.')
    return redirect(url_for('main.item', id=item.id))
  form.subject.data = "Hi! I'm interested on your " + item.name
  return render_template('msg/create.html', form=form, item=item)


@msg.route('/notifications', methods=['GET', 'POST'])
@login_required
def notifications():
  #number of messages of each type
  num_unread = len(current_user.msgs_unread)
  num_sent = current_user.msgs_sent.count()
  num_received = current_user.msgs_received.count()

  if request.method == 'POST':
    if request.form.get('type') == 'unread':
      msgs = current_user.msgs_unread
      n_type = 'Unread'
    elif request.form.get('type') == 'sent':
      msgs = current_user.msgs_sent.order_by(Message.timestamp.desc()).all()
      n_type = 'Sent'
    else:
      msgs = current_user.msgs_received.order_by(Message.timestamp.desc()).all()
      n_type = 'Received'
    return jsonify(type=n_type, msgs=[msg.serialize for msg in msgs],
                    num_unread=num_unread, num_sent=num_sent,
                    num_received=num_received)
  else: #GET request
    msgs = current_user.msgs_unread
    return render_template('msg/notifications.html', msgs=msgs,
                    num_unread=num_unread, num_sent=num_sent,
                    num_received=num_received)


@msg.route('/msg/<int:id>', methods=['GET', 'POST'])
@login_required
def message(id): # pylint: disable=W0622
  msg = Message.query.get_or_404(id)
  if not (current_user == msg.receiver or current_user == msg.sender):
    return redirect(url_for('main.index'))

  #mark message as read if user is the receiver
  if current_user == msg.receiver and msg.unread:
    msg.unread = False
    db.session.add(msg)
    db.session.commit()

  form = MessageForm()
  #do not reply messages to deleted user accounts, to same user or
  #regarding a product that has been deleted
  if msg.item and msg.sender and current_user != msg.sender:
    if form.validate_on_submit():
      reply = Message(subject=form.subject.data,
                      description=form.description.data,
                      sender_id=current_user.id, receiver_id=msg.sender_id,
                      item_id=msg.item_id)
      db.session.add(reply)
      db.session.commit()
      flash('Your message has been sent.')
      return redirect(url_for('msg.notifications'))
  form.subject.data = "Re: " + msg.subject
  return render_template('msg/message.html', msg=msg, item=msg.item, form=form)

vagrant/tradyfit/app/templates/msg/_msg.html
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-envelope-o"></i> {{ msg.subject.capitalize() }}</h3>
  </div>
  <div class="panel-body">
    <p>
    {{ msg.description.capitalize()|default('No description provided', true) }}
    </p>
  </div>
  <div class="panel-footer">
    {% if msg.sender %}
      <h5 class='msg-username'>
        <i>From: @{{ msg.sender.username }}</i>
      </h5>
    {% else %}
      <p>Sorry, this user account has been deleted</p>
    {% endif %}
    <h6><i>{{ moment(msg.timestamp).fromNow(refresh=True) }}</i></h6>
  </div>
</div>

vagrant/tradyfit/app/templates/msg/_msg_reply.html
{% import "bootstrap/wtf.html" as wtf %}

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">
          <i class="fa fa-reply"></i>
          Reply to: <i>@{{ msg.sender.username }}</i>
        </h3>
      </div>
      <div class="panel-body">
        {{ wtf.quick_form(form) }}
      </div>
    </div>
  </div>
</div>

vagrant/tradyfit/app/templates/msg/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}TradyFit - Send message{% endblock %}

{% block page_content %}

<div class="row">
<br><br>
  <div class="col-sm-6 col-md-6" id="msg-creation">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">
          To: <i>@{{ item.user.username }}</i>
          <i class="fa fa-paper-plane-o pull-right"></i>
        </h3>
      </div>
      <div class="panel-body">
        {{ wtf.quick_form(form) }}
      </div>
    </div>
  </div>

  {% include "main/_item_box.html" %}

</div>
{% endblock %}

vagrant/tradyfit/app/templates/msg/message.html
{% extends "base.html" %}

{% block title %}TradyFit - Message{% endblock %}

{% block page_content %}

<div class="row">
  <br><br>
  <div class="col-md-6 col-lg-6" id="msg-{{ msg.id }}">
    {% include "msg/_msg.html" %}

    {% if msg.item and msg.sender and current_user != msg.sender %}
      {% include "msg/_msg_reply.html" %}
    {% endif %}
  </div>

  {% if item %}
    {% include "main/_item_box.html" %}
  {% else %}
    <div class="col-md-5">
      <h5> Sorry, the item related to this message has been deleted</h5>
    </div>
  {% endif %}

</div>

{% endblock %}

vagrant/tradyfit/app/templates/msg/notifications.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
{{ JSGlue.include() }}
<script type=text/javascript src="{{
  url_for('static', filename='js/messages.js') }}"></script>
{% endblock %}

{% block title %}TradyFit - Notifications{% endblock %}

{% block page_content %}
<div class="row">
<br><br>
  <div class="col-sm-4 col-md-3 col-lg-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-inbox"></i>
        Notifications</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <a href="javascript:messages('unread');">Unread</a>
          <span class="badge num-unread">{{ num_unread }}</span>
        </li>
        <li class="list-group-item">
          <a href="javascript:messages('sent');">Sent</a>
          <span class="badge num-sent">{{ num_sent }}</span>
        </li>
        <li class="list-group-item">
          <a href="javascript:messages('received');">Received</a>
          <span class="badge num-received">{{ num_received }}</span>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-sm-8 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading" id="title">Unread</div>
        <ul class="list-group" id="messages">
          {% for msg in msgs %}
            <li class="list-group-item msg" id="msg-{{ msg.id }}">
              <a href="{{ url_for('msg.message', id=msg.id)}}">
              {{ msg.subject }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}