vagrant/tradyfit/app/main/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import StringField, SelectField, SubmitField, \
TextAreaField, DecimalField, ValidationError
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import Required, Length, NumberRange, Regexp
from ..models import Category, User, Country, State
# pylint: disable=E1002

class UserForm(Form):
  username = StringField('Username', validators=[
                      Required(), Length(3, 64), Regexp('^[A-Za-z][.\w]+$', 0,
                      'Username must have only letters, numbers, dots or '
                      'underscores')])

  name = StringField('Name', validators=[
                      Required(), Length(3, 64), Regexp('^[A-Za-z][. \w]+$', 0,
                      'Name must have only letters, numbers, dots or '
                      'underscores')])

  country = SelectField('Country')

  state = SelectField('State (only US)')

  city = StringField('City', validators=[
                      Required(), Length(2, 50), Regexp('^[A-Za-z][ A-Za-z]+$',
                      0, 'City must have only letters')])

  submit = SubmitField('Update')

  def __init__(self, user, *args, **kwargs):
    super(UserForm, self).__init__(*args, **kwargs)
    self.country.choices = Country.get_country_choices()
    self.state.choices = [('NU', 'Not US')] + State.get_us_state_choices()
    self.user = user

  def validate_username(self, field):
    if field.data != self.user.username and \
    User.get_user_by_username(field.data):
      raise ValidationError('Username already in use.')


class DeleteUserForm(Form):
  submit = SubmitField('Delete account')


class ItemForm(Form):
  name = StringField('Name (*)', validators =
                                [ Required(), Length(3, 80),
                                  Regexp('^[A-Za-z0-9][.\- \w]+$', 0,
                                  'Product names must have only letters,'
                                  ' numbers, dots, dashes or underscores')])
  description = TextAreaField('Description', validators=[Length(0,500)])
  price = DecimalField('Price (*)', default=0, places=2,
                        validators= [NumberRange(0, 10**10-1)])
  category = SelectField('Category (*)', coerce=int)
  image = FileField('Image (max. size: 3MB)', validators=[
                    FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                      'Only jpg, png and gif files allowed')])
  submit = SubmitField('Submit')

  def __init__(self, *args, **kwargs):
    super(ItemForm, self).__init__(*args, **kwargs)
    self.category.choices = Category.get_category_choices()

  def validate_image(self, field):
    '''make sure that if image field contains info it is a file'''
    if field.data:
      fr = FileRequired('Image should be a file')
      fr(self, field)


class DeleteItemForm(Form):
  submit = SubmitField('Delete item')


class SearchForm(Form):
  search = StringField('What are you looking for?',
                        validators=[ Required(), Length(3, 80),
                                Regexp('^[A-Za-z0-9][.\- \w]+$', 0,
                                'Search must have only letters,'
                                ' numbers, dots, dashes or underscores')])
  submit = SubmitField('Search')

vagrant/tradyfit/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

vagrant/tradyfit/app/main/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import current_app, render_template, flash, redirect, url_for, \
request, abort, session
from flask.ext.login import current_user, login_required
from . import main
from .. import db
from .forms import UserForm, DeleteUserForm, ItemForm, DeleteItemForm, \
SearchForm
from ..models import Item, Category
from ..helpers import save_item_image, delete_item_image
from ..geolocation import Geolocation


@main.route('/shutdown')
def server_shutdown():
  '''HTTP request to shutdown Werkzeug server running in a background thread
  during functional tests running with Selenium'''
  if not current_app.testing:
    abort(404)
  shutdown = request.environ.get('werkzeug.server.shutdown')
  if not shutdown:
    abort(500)
  shutdown()
  return 'Shutting down...'


@main.route('/', methods=['GET', 'POST'])
def index():
  search_form = SearchForm()
  if search_form.validate_on_submit():
    session['query'] = search_form.search.data #store query on session cookie
    return redirect(url_for('main.search_results'))
  items = Item.query.order_by(Item.timestamp.desc()).limit(4).all()
  #get categories for bottom images links
  swim = Category.get_category('swimming')
  tri = Category.get_category('triathlon')
  soccer = Category.get_category('soccer')
  basket = Category.get_category('basketball')
  baseball = Category.get_category('baseball')
  return render_template('main/index.html', form=search_form, items=items,
    swim=swim.id, tri=tri.id, soccer=soccer.id, basket=basket.id,
    baseball=baseball.id)


@main.route('/items/categories')
def categories():
  '''Show all categories and 12 items. If user is logged in and has
  location, the items are the 12 nearest, if not, show last 12 created
  items'''
  categories = Category.query.all()
  if current_user.is_authenticated() and current_user.has_coordinates():
    user_loc = current_user.get_point_coordinates()
    items = Item.query.order_by(
                        Item.location.distance_box(user_loc)).limit(12).all()
  else:
    items = Item.query.order_by(Item.timestamp.desc()).limit(12).all()
  return render_template('main/categories.html', items=items,
                          categories=categories)


@main.route('/items/category/<int:id>')
def category(id): # pylint: disable=W0622
  city = None
  category = Category.query.get_or_404(id)
  categories = Category.query.all()
  if current_user.is_authenticated() and current_user.has_coordinates():
    user_loc = current_user.get_point_coordinates()
    items = Item.query.filter_by(category=category).order_by(
                        Item.location.distance_box(user_loc)).limit(20).all()
    city = current_user.city
  else:
    items = Item.query.filter_by(category=category).order_by(
                                        Item.timestamp.desc()).limit(20).all()
  return render_template('main/category.html', items=items,
                          categories=categories, category=category, city=city)


@main.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
  items = current_user.items.order_by(Item.timestamp.desc()).all()
  form = UserForm(user=current_user)

  if form.validate_on_submit():
    #if address has changed update user coordinates (lat,lon)
    address = Geolocation.create_address(form.city.data, form.state.data,
                            form.country.data)
    current_user.modify_geolocation(address)

    current_user.username = form.username.data
    current_user.name = form.name.data
    current_user.country = form.country.data
    current_user.state = form.state.data
    current_user.city = form.city.data
    db.session.add(current_user)
    db.session.commit()
    flash('Your profile has been updated.')
    return redirect(url_for('main.profile'))
  form.username.data = current_user.username
  form.name.data = current_user.name
  form.country.data = current_user.country
  form.state.data = current_user.state
  form.city.data = current_user.city
  return render_template('main/profile.html', form=form, items=items)


@main.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
  form = DeleteUserForm()
  if form.validate_on_submit():
    try:
      db.session.delete(current_user)
      db.session.commit()
      session.pop('fb_oauth', None)
      session.pop('last_seen', None)
      flash('We are sorry to see you go...')
    except ValueError:
      flash('Sorry, there was a problem deleting your account. Try again later')
    return redirect(url_for('main.index'))
  return render_template('main/delete_account.html', form=form)


@main.route('/create', methods=['GET', 'POST'])
@login_required
def create():
  if not current_user.has_coordinates():
    flash('Before creating an item, you should have a valid location')
    return redirect(url_for('main.profile'))

  form = ItemForm()

  if form.validate_on_submit():
    #if the filename attribute is empty, assign the default image
    if not (hasattr(form.image.data, 'filename') and form.image.data.filename):
      image = current_app.config["DEFAULT_ITEM"]
    else:
      image = save_item_image(form.image)

    if image:
      category = Category.query.get(form.category.data)
      location = current_user.get_point_coordinates()
      item = Item(name=form.name.data, description=form.description.data,
                  price=form.price.data, category=category, image_url=image,
                  user_id=current_user.id, location=location,
                  country=current_user.country, state=current_user.state,
                  city=current_user.city)
      db.session.add(item)
      db.session.commit()
      flash('Your item has been created.')
      return redirect(url_for('main.index'))
    else:
      flash('Sorry, there was a problem creating your item. Try again later.')
      return redirect(url_for('main.index'))
  return render_template('main/create.html', form=form)


@main.route('/item/<int:id>')
def item(id):  # pylint: disable=W0622
  item = Item.query.get_or_404(id)
  return render_template('main/item.html', item=item)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id): # pylint: disable=W0622
  item = Item.query.get_or_404(id)
  if current_user != item.user:
    return redirect(url_for('main.index'))

  form = ItemForm()
  if form.validate_on_submit():
    # included new image in form and is a file
    if hasattr(form.image.data, 'filename') and form.image.data.filename:
      image = save_item_image(form.image)  # save new image
      if image is None:  # problem uploading new image
        flash('Sorry, there was an error updating your item. Try again later.')
        return redirect(url_for('main.item', id=item.id))
      elif not delete_item_image(item.image_url):  # delete previous image
        delete_item_image(image)  # delete the new image
        flash('Sorry, there was an error updating your item. Try again later.')
        return redirect(url_for('main.item', id=item.id))
    else:  # image not modified
      image = item.image_url

    item.name = form.name.data
    item.description = form.description.data
    item.price = form.price.data
    item.image_url = image
    item.category = Category.query.get(form.category.data)
    item.modified = datetime.utcnow()
    db.session.add(item)
    db.session.commit()
    flash('Your item has been updated.')
    return redirect(url_for('main.item', id=item.id))

  form.name.data = item.name
  form.description.data = item.description
  form.price.data = item.price
  form.category.data = item.category.id
  return render_template('main/edit_item.html', form=form, id=item.id,
                          image=item.image())


@main.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):  # pylint: disable=W0622
  form = DeleteItemForm()
  item = Item.query.get_or_404(id)
  if current_user != item.user:
    return redirect(url_for('main.index'))
  if form.validate_on_submit():
    try:
      db.session.delete(item)
      db.session.commit()
      flash('Your item has been deleted.')
      return redirect(url_for('main.index'))
    except ValueError:
      flash('Sorry, there was a problem deleting your item. Try again later.')
      return redirect(url_for('main.item', id=item.id))
  return render_template('main/delete_item.html', form=form, item=item)


@main.route('/search_results')
def search_results():
  query = session.get('query')
  session.pop('query', None) #remove query from session cookie
  if query:
    city = None
    if current_user.is_authenticated() and current_user.has_coordinates():
      city = current_user.city
      user_loc = current_user.get_point_coordinates()
      res = Item.query.search(query).order_by(
                    Item.location.distance_box(user_loc)).limit(20).all()
    else:
      res = Item.query.search(query).order_by(
                    Item.timestamp.desc()).limit(20).all()
    return render_template('main/search_results.html', query=query, items=res,
                          city=city)
  return redirect(url_for('main.index'))

vagrant/tradyfit/app/templates/main/_category_list.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Categories</h3>
  </div>
  <ul class="list-group">
    {% for category in categories %}
      <li class="list-group-item">
        <a href="{{ url_for('main.category', id=category.id) }}">
        {{ category.name }}</a></li>
    {% endfor %}
  </ul>
</div>

vagrant/tradyfit/app/templates/main/_item.html
<div class="row" id="item-{{ item.id }}">
  <div class="media horizontal-box">
    <span class="media-left">
      <a href="{{ url_for('main.item', id=item.id) }}">
        <img src="{{ item.image() }}" alt="...">
      </a>
    </span>
    <div class="media-body">
      <h3 class="media-heading">
        <a href="{{ url_for('main.item', id=item.id) }}">
          {{ item.name.capitalize()|truncate(50, True) }}
        </a>
        {% if current_user.is_authenticated() and current_user.id == item.user_id %}
          <span class="pull-right">
            <a class="btn btn-xs btn-primary" href="{{ url_for('main.edit', id=item.id) }}">
              <i class="fa fa-pencil-square-o"></i>
            </a>
            <a class="btn btn-xs btn-danger" href="{{ url_for('main.delete', id=item.id) }}">
              <i class="fa fa-trash-o"></i>
            </a>
          </span>
        {% endif %}
      </h3>
      <small>
        <img class="img-circle" src="{{ item.user.avatar() }}" width="20"
        height="20">
        {% if item.modified %}
          Modified {{ moment(item.modified).fromNow(refresh=True) }}
        {% else %}
          Created {{ moment(item.timestamp).fromNow(refresh=True) }}
        {% endif %}
        by <i>@{{ item.user.username }}</i>
      </small>
      <h4>{{ item.description|default('No description provided', true)|truncate(150, True) }}</h4>
      <div class="col-sm-3 col-md-3">
        <h5><b>Price: </b>{{ item.price }}$</h5>
      </div>
      <div class="col-sm-3 col-md-3">
        <h5>
        <i class="fa fa-tags"></i>
        <a href="{{ url_for('main.category', id=item.category_id) }}">
          {{ item.category.name.capitalize() }}</a></h5>
      </div>
      <div class="col-sm-5 col-md-4">
        <h5><i class="fa fa-map-marker"></i> {{ item.address }}</h5>
      </div>
    </div>
  </div>
  <br>
</div>

vagrant/tradyfit/app/templates/main/_item_box.html
<div class="col-xs-12 col-sm-6 col-md-3">
  <div class="thumbnail" id="item-{{ item.id }}">
    <a href="{{ url_for('main.item', id=item.id) }}"><img src="{{ item.image() }}" alt=""></a>
    <div class="caption">
      <div class="row">
        <div class="col-md-12">
          <h4>{{ item.name.capitalize()|truncate(38, True) }}</h4>
          <h5>{{ item.description|default('No description provided', true)|truncate(100, True) }}</h5>
          <h5><b>Price: </b>{{ item.price }}$
          <span class="pull-right">
          <i class="fa fa-tags"></i>
          <a href="{{ url_for('main.category', id=item.category_id) }}">
          {{ item.category.name.capitalize() }}</a></h5>
          </span>
          <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3 col-sm-2 col-md-3 col-lg-3">
          <img class="img-circle" src="{{ item.user.avatar() }}">
        </div>
        <div class="col-xs-7 col-sm-9 col-md-9 col-lg-8">
          <p><i class="fa fa-map-marker"></i> {{ item.address }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

vagrant/tradyfit/app/templates/main/_item_form.html
{% import "bootstrap/wtf.html" as wtf %}

<form action="" method="POST" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

  {{ wtf.form_field(form.name) }}
  {{ wtf.form_field(form.description) }}
  {{ wtf.form_field(form.price) }}
  {{ wtf.form_field(form.category) }}
  {{ wtf.form_field(form.image) }}
  {{ wtf.form_field(form.submit) }}
  <h5><i>All fields marked with (*) are required</i></h5>
</form>

vagrant/tradyfit/app/templates/main/categories.html
{% extends "base.html" %}

{% block title %}TradyFit - Browse categories{% endblock %}

{% block page_content %}

<div class="row">
  <br><br>
  <div class="col-xs-8 col-sm-3 col-md-2">
    {% include "main/_category_list.html" %}
  </div>
  <div class="hidden-xs col-sm-9 col-md-10">
    {% for item in items %}
      {% include "main/_item.html" %}
    {% endfor %}
  </div>
</div>

{% endblock %}

vagrant/tradyfit/app/templates/main/category.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
  {% if city %}
    <h2>Last added items for <i>{{ category.name }}</i> near {{ city}}:</h2>
  {% else %}
    <h2>Last added items for {{ category.name }}:</h2>
  {% endif %}
</div>

<div class="row">
  <div class="hidden-xs hidden-sm col-md-2">
    {% include "main/_category_list.html" %}
  </div>
  <div class="col-xs-12 col-sm-12 col-md-10">
    {% if items %}
      {% if request.MOBILE %}
        {% for item in items %}
          {% include "main/_item_box.html" %}
        {% endfor %}
      {% else %}
        {% for item in items %}
          {% include "main/_item.html" %}
        {% endfor %}
      {% endif %}
    {% else %}
      <h4><i>There's no items created for this category yet</i></h4>
    {% endif %}
  </div>
</div>

{% endblock %}

vagrant/tradyfit/app/templates/main/create.html
{% extends "base.html" %}

{% block title %}TradyFit - List an item{% endblock %}

{% block page_content %}

<div class="row">
  <br>
  <div class="col-md-6 col-lg-6" id="item-creation">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">List your item
        <i class="fa fa-cubes pull-right"></i></h3>
      </div>
      <div class="panel-body">
        {% include "main/_item_form.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

vagrant/tradyfit/app/templates/main/delete_account.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Delete account</h1>
</div>

<div class="row">
  <div class="col-md-4" id="delete-account">
    <p>By deleting your account, all your items will be gone. This is a non reversible action.</p>

    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

vagrant/tradyfit/app/templates/main/delete_item.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="row">
<br><br>
  <div class="col-md-6" id="delete-account">
    <p><b>Warning!</b> This is a non reversible action. <br>
    Are you sure you want to delete your item? </p>

    {{ wtf.quick_form(form) }}
    <br><br>
  </div>
  <div>
    {% include "main/_item_box.html" %}
  </div>
</div>
{% endblock %}

vagrant/tradyfit/app/templates/main/edit_item.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TradyFit - Edit item{% endblock %}

{% block page_content %}
<div class="row">
<br><br>
  <div class="col-sm-7 col-md-6 col-lg-6" id="edit-item-{{ id }}">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Edit your item
        <i class="fa fa-pencil-square-o pull-right"></i></h3>
      </div>
      <div class="panel-body">
        {% include "main/_item_form.html" %}
      </div>
    </div>
  </div>
  <div class="col-sm-5 col-md-5 col-lg-5" id="item-image-{{ id }}">
    <img class="img-thumbnail" src="{{ image }}">
  </div>
</div>
{% endblock %}

vagrant/tradyfit/app/templates/main/index.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TradyFit{% endblock %}

{% block head %}
{{ super() }}
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="shortcut icon" href="{{ url_for('static',
filename='img/favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}"
type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block navbar %}
  {% include '_navbar.html' %}
{% endblock %}

{% block content %}

<div id="headerwrap" class='row centered bckgimage'>
  <h1><b>Train. Sweat. Repeat.<b></h1>
  <h2>Enjoy your favorite sport on a budget</h2>
</div><!-- headerwrap -->

<div id="wh">
  <div class="container">
    <div class="row centered">
      <div class="col-md-6 col-md-offset-3">
        <h1>What are you looking for?</h1>
        <form action="{{url_for('main.index')}}" class="form-inline"
        method="POST" id="search-form">
          {{ form.hidden_tag() }}
          <div class="form-group">
            <input id="search" name="search" class="form-control"
            placeholder="triathlon bike, surf table, ..." type="text" size="35">
          </div>
          <button type="submit" class="btn btn-primary" id="submit-search">Search</button>
          {% if form.errors.items() %}
            <br><i class='error-msg'>{{ form.errors.items()[0][1][0] }}</i>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>

<div id="lg">
  <div class="container">
    <div class="row alert-section">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        {% for message in get_flashed_messages() %}
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      </div>
      <div class="col-md-2"></div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <h2>Last added items</h2>
      </div>
    </div>
    <div class="row" id="items">
      {% for item in items %}
        {% include "main/_item_box.html" %}
      {% endfor %}
    </div>
    <div class="row">
      <div class="col-md-6">
        <h2>Browse by Top Categories</h2>
      </div>
    </div>
    <div class="row top-categories">
      <div class="hidden-xs col-md-12 col-lg-8">
      <a href="{{ url_for('main.category', id=swim) }}">
        <img src="{{ url_for('static', filename='img/swim.jpg') }}">
      </a>
      </div>
      <div class="col-lg-3 pull-left">
      <a href="{{ url_for('main.category', id=tri) }}">
        <img src="{{ url_for('static', filename='img/tri.jpg') }}">
      </a>
      </div>
      <div class="col-lg-4">
      <a href="{{ url_for('main.category', id=soccer) }}">
        <img src="{{ url_for('static', filename='img/soccer.jpg') }}">
      </a>
      </div>
      <div class="col-lg-4 pull-left">
      <a href="{{ url_for('main.category', id=basket) }}">
        <img src="{{ url_for('static', filename='img/basketball.jpg') }}">
      </a>
      </div>
      <div class="col-lg-4">
      <a href="{{ url_for('main.category', id=baseball) }}">
        <img src="{{ url_for('static', filename='img/baseball.jpg') }}">
      </a>
      </div>
    </div>
    <br><br>
  </div>
</div>

<div id="footer">
  {% include 'footer.html' %}
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
<script type=text/javascript>
$(function () {
  //remove #_=_ added from FB login redirect
  if (window.location.hash == '#_=_'){
      history.replaceState
          ? history.replaceState(null, null,
                       window.location.href.split('#')[0])
          : window.location.hash = '';
  };
});
</script>
{% endblock %}

vagrant/tradyfit/app/templates/main/item.html
{% extends "base.html" %}

{% block title %}TradyFit - Item{% endblock %}

{% block page_content %}
<div class="row item-view">
<br><br>
  <div class="col-xs-11 col-sm-6 col-md-6" id="item-{{item.id}}">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          {{ item.name.capitalize() }}
        </h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <i class="fa fa-map-marker"></i> {{ item.address }}
          <span class="pull-right">
            <i class="fa fa-tags"></i>
            <a href="{{ url_for('main.category', id=item.category_id) }}">
              {{ item.category.name.capitalize() }}
            </a>
          </span>
          <br><b>Price: </b>{{ item.price }}$
        </li>
      </ul>
      <div class="panel-body">
        {{ item.description|default('No description provided', true) }}
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-xs-2 col-sm-3 col-md-2" id="owner-avatar">
            <img class="img-circle" src="{{ item.user.avatar() }}" height="50"
            width="50">
          </div>
          <div class="col-xs-8 col-sm-7 col-md-6" id="owner-info">
            {% if item.modified %}
              <h5>Modified {{ moment(item.modified).fromNow(refresh=True) }}
            {% else %}
              <h5>Created {{ moment(item.timestamp).fromNow(refresh=True) }}
            {% endif %}
              by <i>@{{ item.user.username }}</i></h5>
          </div>
        </div>
      </div>
    </div>
    {% if current_user.is_authenticated() and current_user.id != item.user_id %}
      <p><a href="{{ url_for('msg.create', id=item.id) }}" class="btn btn-primary">Contact seller</a></p>
    {% endif %}
    {% if current_user.is_authenticated() and current_user.id == item.user_id %}
      <p><a href="{{ url_for('main.edit', id=item.id) }}">Edit</a> |
      <a href="{{ url_for('main.delete', id=item.id) }}">Delete</a></p>
    {% endif %}
    <br>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-5 pull-right" id="item-image">
    <img class="img-thumbnail" src="{{ item.image() }}">
  </div>
</div>
{% endblock %}

vagrant/tradyfit/app/templates/main/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TradyFit - Profile{% endblock %}

{% block page_content %}

<div class="row">
  <br><br>
  <div class="col-sm-4 col-md-3 col-lg-3" id="user-avatar">
    <img class="img-circle profile-avatar" src="{{ current_user.avatar() }}">
    <br><h3>@{{ current_user.username }}</h3>
  </div>
  <div class="col-sm-5 col-md-4" id="user-form">
    <div class="panel panel-warning">
      <div class="panel-body">
        {{ wtf.quick_form(form) }}
      </div>
      <div class="panel-footer">
        <a href="{{ url_for('main.delete_account') }}">Delete account</a>
      </div>
    </div>
  </div>
</div>

<div class="page-header">
{% if not items %}
  <h2>You haven't created any items yet</h2>
{% else %}
  <h1>Your listed items</h1>
{% endif %}
</div>

{% if request.MOBILE %}
  {% for item in items %}
    {% include "main/_item_box.html" %}
  {% endfor %}
{% else %}
  {% for item in items %}
    {% include "main/_item.html" %}
  {% endfor %}
{% endif %}
<br><br>
{% endblock %}

vagrant/tradyfit/app/templates/main/search_results.html
{% extends "base.html" %}

{% block title %}TradyFit - Search Results{% endblock %}

{% block page_content %}
<div class="page-header">
  {% if city %}
    <h2>Search results for "{{ query }}" near {{ city }}:</h2>
  {% else %}
    <h2>Search results for "{{ query }}":</h2>
  {% endif %}
</div>

{% if items %}
  {% if request.MOBILE %}
    {% for item in items %}
      {% include "main/_item_box.html" %}
    {% endfor %}
  {% else %}
    {% for item in items %}
      {% include "main/_item.html" %}
    {% endfor %}
  {% endif %}
{% else %}
  <h4><i>Sorry, there's no items that matches your search</i></h4>
{% endif %}

{% endblock %}